name = "Yunir"
uuid = "6ba116df-6904-454d-b214-90038a8281a6"
authors = ["Al-Ahmadgaid B. Asaad"]
version = "0.2.5"

[deps]
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
QuranTree = "f647ab69-6f05-4d64-883f-59d0fbe08d2b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BioAlignments = "2.0.0"
CairoMakie = "0.8.8"
Colors = "0.12.8"
Makie = "0.17.8"
julia = "1.6.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
